quotes_app/quotes_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls"))
]

quotes_app/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from .forms import LoginForm
from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html", form_class=LoginForm),
        name="login",
    ),
    # path('logout/', LogoutView.as_view(), name='logout'),
    path("logout/", views.logoutuser, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

quotes_app/users/models.py
from django.db import models

# Create your models here.

quotes_app/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import CharField, EmailField, EmailInput, TextInput, PasswordInput

class SignUpForm(UserCreationForm):
    username = CharField(max_length=30, min_length=3, required=True, widget=TextInput(attrs={"class":"form-control"}))
    email = EmailField(max_length=30, min_length=3, required=True, widget=EmailInput(attrs={"class":"form-control"}))
    password1 = CharField(min_length=3, required=True, widget=PasswordInput(attrs={"class":"form-control"}))
    password2 = CharField(min_length=3, required=True, widget=PasswordInput(attrs={"class":"form-control"}))
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
class LoginForm(AuthenticationForm):
    username = CharField(max_length=30, min_length=3, required=True, widget=TextInput(attrs={"class":"form-control"}))
    password = CharField(min_length=3, required=True, widget=PasswordInput(attrs={"class":"form-control"}))
    
    class Meta:
        model = User
        fields = ('username', 'password')

quotes_app/users/views.py
from django.shortcuts import redirect, render
from django.views import View
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

from .forms import SignUpForm
# Create your views here.


class SignUpView(View):
    template_name = "users/signup.html"
    form_class = SignUpForm
    
    def get(self, request):
        return render(request, self.template_name, context={"form":self.form_class})
    
    def post(self, request):
        if request.user.is_authenticated:
            return redirect(to='quotes:main')
        
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:main")
        else:
            messages.info(request, "шось не так")
            return render(request, 'users/signup.html', context={"form": form})
      
@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:main')  
     
class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'   
            

quotes_app/users/templates/users/login.html
{% extends "quotes/base.html" %} {% block content %}
<h3>LogIn</h3>
<form method="post">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username {{form.username}}</label>
  </div>
  <div class="mb-3">
    <label class="form-label">Password {{form.password}}</label>
  </div>
  <div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
      {{ message }}
    </div>
    {% endfor %}
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
  <div class="small text-center">
    <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
  </div>
</form>

{% endblock content %}

quotes_app/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

quotes_app/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

quotes_app/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

quotes_app/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quotes_app/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

quotes_app/users/templates/users/signup.html
{% extends "quotes/base.html" %} {% block content %}
<h3>SignUp</h3>
<form method="post">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username {{form.username}}</label>
    {% if form.username.errors %}
      <div class="alert alert-danger">
        {{ form.username.errors }}
      </div>
    {% endif %}
  </div>
  <div class="mb-3">
    <label class="form-label">Email address {{form.email}}</label>
    {% if form.email.errors %}
      <div class="alert alert-danger">
        {{ form.email.errors }}
      </div>
    {% endif %}
  </div>
  <div class="mb-3">
    <label class="form-label">Password {{form.password1}}</label>
    {% if form.password1.errors %}
      <div class="alert alert-danger">
        {{ form.password1.errors }}
      </div>
    {% endif %}
  </div>
  <div class="mb-3">
    <label class="form-label">Repeat password {{form.password2}}</label>
    {% if form.password2.errors %}
      <div class="alert alert-danger">
        {{ form.password2.errors }}
      </div>
    {% endif %}
  </div>
  <div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
      {{ message }}
    </div>
    {% endfor %}
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock content %}