quotes_app/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"
urlpatterns = [
    path("", views.main, name="main"),
    path("<int:page>", views.main, name="root_paginate"),
    path("author/<int:author_id>", views.author_detail, name="author_detail"),
    path("tag/<int:tag_id>", views.tag, name="tag"),
    path("adding_tag", views.add_tag, name="tag_input"),
    path("adding_author", views.add_author, name="author_input"),
    path("adding_quote", views.add_quote, name="quote_input"),
]

quotes_app/quotes_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls"))
]

quotes_app/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from .forms import LoginForm
from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html", form_class=LoginForm),
        name="login",
    ),
    # path('logout/', LogoutView.as_view(), name='logout'),
    path("logout/", views.logoutuser, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

quotes_app/quotes/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False)
    
class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    

def get_top_10_tags():
    return Tag.objects.annotate(num_quotes=models.Count('quote')).order_by('-num_quotes')[:10]

quotes_app/quotes/forms.py
from django import forms

from .models import *


class AuthorForm(forms.ModelForm):
    fullname = forms.CharField(
        min_length=5,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control", "id": "fullnameInput"}),
    )

    born_date = forms.CharField(
        min_length=8,
        widget=forms.TextInput(attrs={"class": "form-control", "id": "dateBirthInput"}),
    )
    
    born_location = forms.CharField(
        min_length=5,
        widget=forms.TextInput(attrs={"class": "form-control", "id": "locationBirthInput"}),
    )
    
    description = forms.CharField(
        min_length=5,
        widget=forms.Textarea(attrs={"class": "form-control", "id": "descriptionTextarea"}),
    )

    class Meta:
        model = Author
        fields = ("fullname", "born_date", "born_location", "description")


class TagForm(forms.ModelForm):
    name = forms.CharField(
        min_length=2,
        max_length=30,
        widget=forms.TextInput(attrs={}),
    )
    
    class Meta:
        model = Tag
        fields = ("name",)


class QuoteForm(forms.ModelForm):
    quote = forms.CharField(
        required=True, 
        widget=forms.TextInput(attrs={"class": "form-control", "id": "quoteInput"})
    )

    class Meta:
        model = Quote
        fields = ("quote",)
        exclude = ["tags", "author"]

quotes_app/quotes/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .forms import *
from .models import *
from .utils import *


# Create your views here.
def main(request, page=1):
    quotes = Quote.objects.filter().all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    tags_top = get_top_10_tags()
    return render(
        request,
        "quotes/index.html",
        context={"quotes": quotes_on_page, "top_tags": tags_top},
    )


def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, "quotes/author.html", context={"author": author})


def tag(request, tag_id):
    tag = get_object_or_404(Tag, pk=tag_id)
    quotes = Quote.objects.filter(tags=tag)
    tags_top = get_top_10_tags()
    return render(
        request,
        "quotes/tag.html",
        context={"tag": tag, "quotes": quotes, "top_tags": tags_top},
    )


@login_required
def add_tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:main")
        else:
            return render(request, "quotes/tag_input.html", {"form": form})
    return render(request, "quotes/tag_input.html", {"form": TagForm()})


@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:main")
        else:
            return render(request, "quotes/author_input.html", {"form": form})
    return render(request, "quotes/author_input.html", {"form": AuthorForm()})


@login_required
def add_quote(request):
    tags = Tag.objects.filter().all()
    authors = Author.objects.filter().all()
    
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            
            author_id = request.POST["author"]
            author_choise = Author.objects.filter(pk=author_id).first()
            new_quote.author = author_choise
            
            new_quote.save()
            
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
                
            return redirect(to="quotes:main")
        else:
            return render(request, "quotes/quote_input.html", {"form": form, "tags":tags, "authors":authors})
    return render(request, "quotes/quote_input.html", {"form": QuoteForm(), "tags":tags, "authors":authors})
    

quotes_app/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %} {% block content %}

<div class="author-details">
  <h3 class="author-title">{{author.fullname}}</h3>
  <p>
    <strong>Born:</strong>
    <span class="author-born-date">{{author.born_date}}</span>
    <span class="author-born-location">{{author.born_location}}</span>
  </p>
  <p><strong>Description:</strong></p>
  <div class="author-description">{{author.description}}</div>
</div>

{% endblock content %}

quotes_app/quotes/templates/quotes/author_input.html
{% extends "quotes/base.html" %} {% block content %}
<div class="container mt-2">
  <h3>Add Author</h3>
  <form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="fullnameInput" class="form-label">Fullname</label>
      {{ form.fullname }}
      {% if form.fullname.errors %}
        <div class="alert alert-danger">
          {{ form.fullname.errors }}
        </div>
      {% endif %}
    </div>
    <div class="mb-3">
      <label for="dateBirthInput" class="form-label">Date of Birth</label>
      {{ form.born_date }}
      {% if form.born_date.errors %}
        <div class="alert alert-danger">
          {{ form.born_date.errors }}
        </div>
      {% endif %}
    </div>
    <div class="mb-3">
      <label for="locationBirthInput" class="form-label">Birth Location</label>
      {{ form.born_location }}
      {% if form.born_location.errors %}
        <div class="alert alert-danger">
          {{ form.born_location.errors }}
        </div>
      {% endif %}
    </div>
    <div class="mb-3">
      <label for="descriptionTextarea" class="form-label">Description</label>
      {{ form.description }}
      {% if form.description.errors %}
        <div class="alert alert-danger">
          {{ form.description.errors }}
        </div>
      {% endif %}
    </div>
    <input class="btn btn-primary" type="submit" value="Submit" />
    <input class="btn btn-secondary" type="reset" value="Reset" />
  </form>
</div>
{% endblock content %}

quotes_app/quotes/templates/quotes/base.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
    crossorigin="anonymous"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static "quotes/style.css" %}"> 
    <title>Quotes Homework</title>
  </head>
  <body>
    <script src="" async defer></script>

    <div class="container">
      <div class="row header-box pt-3">
        <div class="col-md-8">
          <h1>
            <a href="/" style="text-decoration: none">Quotes Homework</a>
          </h1>
        </div>
        <div class="col-md-4">
          <p>
            {% if user.is_authenticated %}
            <a href="{% url 'users:logout'%}" class="btn btn-secondary">Logout</a>
            {% else %}
            <a href="{% url 'users:signup'%}" class="btn btn-primary">SignUp</a>
            <a href="{% url 'users:login'%}" class="btn btn-primary">Login</a>
            {% endif %}
          </p>
        </div>
        {% if user.is_authenticated %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <a href="{% url 'quotes:quote_input'%}" class="btn btn-primary">Add Quote</a>
          <a href="{% url 'quotes:author_input'%}" class="btn btn-primary">Add Athor</a>
          <a href="{% url 'quotes:tag_input'%}" class="btn btn-primary">Add Tag</a>
        </div>
        {% endif %}
      </div>
      {% block content %}{% endblock content %}
    </div>
  </body>
</html>

quotes_app/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %} {% load extract %} 
{% block content %} 
{% block tag_content %} {% endblock tag_content %}
<div class="row">
  <div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">{{quote.quote}}</span>
      <span
        >by {% if quote.author %}
        <small class="author" itemprop="author"
          >{{ quote.author.fullname }}</small
        >
        <a href="{% url 'quotes:author_detail' quote.author.id %}">(about)</a>
        {% else %}
        <small class="author" itemprop="author">Unknown Author</small>
        {% endif %}
      </span>
      <div class="tags">
        Tags: {% for tag in quote.tags.all %}
        <a class="tag" href="{% url 'quotes:tag' tag.id %}">{{tag.name}}</a>
        {% endfor %}
      </div>
    </div>
    {% endfor %}

    <nav>
      <ul class="pager">
        {% if quotes.has_previous %}
        <li class="previous">
          <a
            href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}"
            ><span aria-hidden="true">←</span> Previous</a
          >
        </li>
        {% endif %} {% if quotes.has_next %}
        <li class="next">
          <a
            href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}"
            >Next <span aria-hidden="true">→</span></a
          >
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>

  <div class="col-md-4 tags-box">
    <h2>Top Ten tags</h2>
    {% for tag in top_tags %}
    <span class="tag-item">
      <a
        class="tag"
        style="font-size: 24px"
        href="{% url 'quotes:tag' tag.id %}"
        >{{ tag.name }}</a
      >
    </span>
    {% endfor %}
  </div>
</div>

{% endblock content %}

quotes_app/quotes/templates/quotes/quote_input.html
{% extends "quotes/base.html" %} {% block content %}
<div class="container mt-2">
  <h3>Add Quote</h3>
  <form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="quoteInput" class="form-label">Quote</label>
      {{ form.quote }}
      {% if form.quote.errors %}
        <div class="alert alert-danger">
          {{ form.quote.errors }}
        </div>
      {% endif %}
    </div>
    <div class="mb-3">
      <label for="tags" class="form-label">Tags</label>
      <select class="form-select" size="6" name="tags" multiple="multiple" required>
        {% for tag in tags %}
          <option value="{{tag.name}}">{{tag.name}}</option>
        {% endfor %}
      </select>
      {% if form.tags.errors %}
        <div class="alert alert-danger">
          {{ form.tags.errors }}
        </div>
      {% endif %}
    </div>
    <div class="mb-3">
      <label for="authorSelect" class="form-label">Author</label>
      <select class="form-select" name="author" required>
        {% for author in authors %}
          <option value="{{author.id}}">{{author.fullname}}</option>
        {% endfor %}
      </select>
      {% if form.author.errors %}
        <div class="alert alert-danger">
          {{ form.author.errors }}
        </div>
      {% endif %}
    </div>
    <input class="btn btn-primary" type="submit" value="Submit" />
    <input class="btn btn-secondary" type="reset" value="Reset" />
  </form>
</div>
{% endblock content %}

quotes_app/quotes/templates/quotes/tag.html
{% extends "quotes/index.html" %}

{% block tag_content %}
<h3> Quotes tagged with "{{ tag.name }}"</h3>

{% endblock tag_content %}

quotes_app/quotes/templates/quotes/tag_input.html
{% extends "quotes/base.html" %} {% block content %}
<div class="container mt-2">
  <h3>Add Tag</h3>
  <form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="nameInput" class="form-label">Tag</label>
      {{ form.name }}
      {% if form.name.errors %}
        <div class="alert alert-danger">
          {{ form.name.errors }}
        </div>
      {% endif %}
    </div>
    <input class="btn btn-primary" type="submit" value="Submit" />
    <input class="btn btn-secondary" type="reset" value="Reset" />
  </form>
</div>
{% endblock content %}